services:
  postgres:
    image: postgres:16-alpine
    container_name: sabadyar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sabadyar
      POSTGRES_PASSWORD: sabadyar
      POSTGRES_DB: sabadyar
    ports:
      - "5432:5432"
    volumes:
      - sabadyar_pg:/var/lib/postgresql/data

volumes:
  sabadyar_pg:
